set_property SRC_FILE_INFO {cfile:C:/Users/SET253-04U.HCCMAIN/Documents/GitHub/ENES247-master/ENES247_Yakin/lab1-mux/lab1_1_mux2-1-1bitwide/lab1_1_mux2-1-1bitwide.srcs/constrs_1/imports/lab1_1_mux2-1-1bitwide/Nexys4DDR_Master.xdc rfile:../../../lab1_1_mux2-1-1bitwide.srcs/constrs_1/imports/lab1_1_mux2-1-1bitwide/Nexys4DDR_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { x }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS33 } [get_ports { y }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS33 } [get_ports { s }]; #IO_L6N_T0_D08_VREF_14 Sch=sw[2]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { m }]; #IO_L18P_T2_A24_15 Sch=led[0]
