# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mert Akin/Documents/GITHUB/ENES245_YAKIN/lab9-StopWatch/lab9_3_3/lab9_3_3.srcs/sources_1/ip/counter_6Bit_dsp48/counter_6Bit_dsp48.xci
# IP: The module: 'counter_6Bit_dsp48' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mert Akin/Documents/GITHUB/ENES245_YAKIN/lab9-StopWatch/lab9_3_3/lab9_3_3.srcs/sources_1/ip/counter_6Bit_dsp48/counter_6Bit_dsp48_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_6Bit_dsp48'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Mert Akin/Documents/GITHUB/ENES245_YAKIN/lab9-StopWatch/lab9_3_3/lab9_3_3.srcs/sources_1/ip/counter_6Bit_dsp48/counter_6Bit_dsp48.xci
# IP: The module: 'counter_6Bit_dsp48' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mert Akin/Documents/GITHUB/ENES245_YAKIN/lab9-StopWatch/lab9_3_3/lab9_3_3.srcs/sources_1/ip/counter_6Bit_dsp48/counter_6Bit_dsp48_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_6Bit_dsp48'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
