# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Mert Akin/Documents/GITHUB/ENES245_YAKIN/lab9-StopWatch/lab9_2_3/Nexys4DDR_Master.xdc

# IP: ip/counter_8Bit_fabric/counter_8Bit_fabric.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_8Bit_fabric || ORIG_REF_NAME==counter_8Bit_fabric} -quiet] -quiet
