# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Mert Akin/Documents/GITHUB/ENES245_YAKIN/lab8-IntellectualProperty/lab8_1_2/Nexys4DDR_Master.xdc

# IP: ip/clk_5MHz/clk_5MHz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_5MHz || ORIG_REF_NAME==clk_5MHz} -quiet] -quiet
