# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Mert Akin/Documents/GITHUB/ENES245_YAKIN/lab8-IntellectualProperty/lab8_2_1/Nexys4DDR_Master.xdc

# IP: ip/four_bit_counter_fabric_1/four_bit_counter_fabric.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==four_bit_counter_fabric || ORIG_REF_NAME==four_bit_counter_fabric} -quiet] -quiet
